name: Go

on:
  push:
    tags:
    - v*

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Create release on GitHub
      uses: goreleaser/goreleaser-action@v2
      with:
        # GoReleaser 版本
        version: latest
        # 传递给 GoReleaser 的参数
        args: release --rm-dist
      env:
        # 提供访问仓库token
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
